name: ClassImbalance
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - affine=2.4.0
  - attrs=25.4.0
  - blosc=1.21.6
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - click=8.3.1
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - expat=2.7.3
  - freexl=2.0.0
  - geos=3.10.6
  - geotiff=1.7.0
  - giflib=5.2.2
  - icu=73.2
  - jpeg=9e
  - json-c=0.18
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libarchive=3.8.2
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcurl=8.18.0
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgdal-core=3.11.4
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libkml=1.3.0
  - liblapack=3.11.0
  - libnghttp2=1.67.0
  - libnsl=2.0.0
  - libopenblas=0.3.30
  - libpng=1.6.53
  - libspatialite=5.1.0
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=1.41.5
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - minizip=4.0.7
  - ncurses=6.5
  - openssl=3.6.0
  - pcre2=10.46
  - pip=25.3
  - proj=9.3.1
  - pthread-stubs=0.3
  - pyparsing=3.3.1
  - python=3.11.14
  - python_abi=3.11
  - rasterio=1.4.4
  - readline=8.3
  - setuptools=80.9.0
  - snappy=1.2.2
  - sqlite=3.51.1
  - tk=8.6.15
  - uriparser=0.9.8
  - wheel=0.45.1
  - xerces-c=3.3.0
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - albumentations==1.4.3
      - anyio==4.12.1
      - arrow==1.4.0
      - beautifulsoup4==4.14.3
      - blessed==1.25.0
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - croniter==1.3.15
      - cycler==0.12.1
      - dateutils==0.6.12
      - deepdiff==7.0.1
      - editor==1.6.6
      - einops==0.8.1
      - fastapi==0.88.0
      - filelock==3.20.3
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2023.12.2
      - ftfy==6.3.1
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.3.1
      - idna==3.11
      - imageio==2.37.2
      - inquirer==3.4.1
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lightning==2.0.0
      - lightning-cloud==0.6.0
      - lightning-utilities==0.15.2
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.6.1
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - ordered-set==4.1.0
      - packaging==24.2
      - pillow==12.1.0
      - propcache==0.4.1
      - protobuf==6.33.3
      - psutil==6.1.1
      - pydantic==1.10.26
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.3.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - readchar==4.2.1
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - runs==1.2.2
      - safetensors==0.7.0
      - scikit-image==0.26.0
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - segmentation-models-pytorch==0.5.0
      - shellingham==1.5.4
      - six==1.17.0
      - soupsieve==2.8.1
      - starlette==0.22.0
      - starsessions==1.3.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tifffile==2025.12.20
      - timm==1.0.24
      - torch==2.9.1
      - torchmetrics==1.8.2
      - torchvision==0.24.1
      - tqdm==4.67.1
      - triton==3.5.1
      - ttach==0.0.3
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.3
      - uvicorn==0.40.0
      - websocket-client==1.9.0
      - websockets==11.0.3
      - werkzeug==3.1.5
      - xmod==1.8.1
      - yarl==1.22.0
prefix: /home/lainey/miniconda3/envs/ClassImbalance
